# https://github.com/graalvm/graalvm-demos/blob/master/spring-native-image/Dockerfiles/Dockerfile
FROM container-registry.oracle.com/graalvm/native-image:21-ol8 AS builder
WORKDIR /app

COPY hello-app-native .

RUN ./mvnw --no-transfer-progress native:compile -Pnative -DskipTests

FROM container-registry.oracle.com/os/oraclelinux:9-slim
EXPOSE 8080

COPY --from=builder /build/target/hello-app hello-app
ENTRYPOINT ["/hello-app"]